[tool.poetry]
name = "ovh-server"
version = "0.1.0"
description = ""
authors = ["SAGON NICOLAS <sagon.nicolas@gmail.com>"]
readme = "README.md"
packages = [
    { include = "lib"},
    { include = "main_stack"},
    { include = "data" }
]

[tool.poetry.dependencies]
python = "^3.13"
pulumi = "^3.100.0"
pyright = "^1.1.402"
pulumi-ovh = "^2.5.0"
